tripal.settings:
  type: config_object
  label: Tripal Settings
  mapping:
    tripal_entity_type:
      type: config_object
      mapping:
        max_id:
          type: integer
    files:
      type: config_object
      mapping:
        max_size:
          type: integer
        quota:
          type: integer
        expiration:
          type: integer
